# Generated by Django 5.2 on 2025-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("commune_nom", models.CharField(max_length=255, verbose_name="commune")),
                (
                    "adresse_depot",
                    models.CharField(blank=True, max_length=255, verbose_name="adresse"),
                ),
                ("date_constat", models.DateField(verbose_name="date")),
                ("heure_constat", models.TimeField(verbose_name="heure")),
                (
                    "auteur_signalement",
                    models.CharField(blank=True, max_length=255, verbose_name="auteur"),
                ),
                (
                    "nature_terrain",
                    models.CharField(blank=True, max_length=255, verbose_name="terrain"),
                ),
                (
                    "volume_dechets",
                    models.CharField(blank=True, max_length=255, verbose_name="volume"),
                ),
                (
                    "types_dechets",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="types"),
                ),
                ("precisions_dechets", models.TextField(blank=True, verbose_name="précisions")),
                ("has_photos", models.BooleanField(default=False, verbose_name="photos")),
                ("auteur_identifie", models.BooleanField(default=False, verbose_name="identifié")),
                (
                    "souhaite_porter_plainte",
                    models.BooleanField(default=False, verbose_name="plainte"),
                ),
                (
                    "indices_disponibles",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="indices"),
                ),
            ],
            options={
                "verbose_name": "signalement",
                "verbose_name_plural": "signalements",
            },
        ),
    ]
